pool:
  vmImage: VS2017-Win2016

trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]

steps:

- powershell: |
    . 'build/Update-Version.ps1'

    Update-Version $env:BUILD_BUILDID `
        -CommitHash $env:BUILD_SOURCEVERSION.Substring(0, 8) `
        -UpdateBuildNumber {
            param([string] $BuildNumber)
            Write-Host "##vso[build.updatebuildnumber]$BuildNumber"
        }
  displayName: 'Update version'

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: src
    msbuildArgs: /restore /p:DeployExtension=false
    configuration: Release

- task: VSTest@2
  displayName: Test

- task: PublishBuildArtifacts@1
  displayName: Save VSIX artifact
  inputs:
    PathtoPublish: src/CopyFunctionBreakpointName/bin/Release/CopyFunctionBreakpointName.vsix
    ArtifactName: VSIX

- task: PublishBuildArtifacts@1
  displayName: Save symbols
  inputs:
    PathtoPublish: src/CopyFunctionBreakpointName/bin/Release/CopyFunctionBreakpointName.pdb
    ArtifactName: Symbols
