pool:
  vmImage: VS2017-Win2016

steps:
- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '**/*.sln'
    msbuildArgs: /restore /p:DeployExtension=false
    configuration: Release

- task: VSTest@2
  displayName: Test

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: src/CopyFunctionBreakpointName/bin/Release/CopyFunctionBreakpointName.vsix
    ArtifactName: VSIX
